-- Nortek Aquadopp module. Requires rejected_observations. Private rows use
-- _<site>_AQUADOPP and public rows use <site>-WQ in nortek_aquadopp.
CREATE FUNCTION aquadopp_public_station(p varchar) RETURNS varchar LANGUAGE sql IMMUTABLE STRICT AS $$ SELECT CASE WHEN p ~ '^_.+_AQUADOPP$' THEN regexp_replace(p,'^_(.+)_AQUADOPP$',E'\\1-WQ') END $$;
CREATE FUNCTION aquadopp_source_station(p varchar) RETURNS varchar LANGUAGE sql IMMUTABLE STRICT AS $$ SELECT CASE WHEN p ~ '^.+-WQ$' THEN '_'||regexp_replace(p,'-WQ$','')||'_AQUADOPP' END $$;
CREATE FUNCTION aquadopp_resolve_serial(p_station varchar,p_m_date timestamptz) RETURNS varchar LANGUAGE sql STABLE AS $$ SELECT NULLIF(btrim(serial_number_aquadopp),'') FROM nortek_aquadopp WHERE station=p_station AND m_date=p_m_date $$;
CREATE FUNCTION aquadopp_apply_active_rejections(p_station varchar,p_serial varchar,p_m_date timestamptz) RETURNS void LANGUAGE plpgsql AS $$
DECLARE r record; BEGIN
 FOR r IN SELECT * FROM rejected_observations WHERE active AND source_table='nortek_aquadopp' AND public_table='nortek_aquadopp' AND instrument_type='Nortek Aquadopp' AND source_station=p_station AND m_date=p_m_date LOOP
  UPDATE nortek_aquadopp SET current_speed=CASE WHEN r.public_parameter='current_speed' THEN NULL ELSE current_speed END,qc_current_speed=CASE WHEN r.public_parameter='current_speed' THEN r.qc_flag ELSE qc_current_speed END,current_direction=CASE WHEN r.public_parameter='current_direction' THEN NULL ELSE current_direction END,qc_current_direction=CASE WHEN r.public_parameter='current_direction' THEN r.qc_flag ELSE qc_current_direction END WHERE station=r.public_station AND m_date=r.m_date;
 END LOOP; END $$;
CREATE FUNCTION reject_aquadopp_public_parameter(p_source_station varchar,p_serial_number_aquadopp varchar,p_m_date timestamptz,p_public_parameter varchar,p_qc_flag integer,p_rejection_reason varchar,p_rejected_by varchar DEFAULT current_user,p_source_query_or_script text DEFAULT NULL) RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE v_serial varchar;v_id bigint;v_public varchar; BEGIN
 v_public:=aquadopp_public_station(p_source_station); IF v_public IS NULL OR p_public_parameter NOT IN ('current_speed','current_direction') THEN RAISE EXCEPTION 'unsupported Aquadopp identity or public parameter'; END IF;
 IF NOT EXISTS(SELECT 1 FROM nortek_aquadopp WHERE station=p_source_station AND m_date=p_m_date) THEN RAISE EXCEPTION 'Aquadopp source observation not found'; END IF; v_serial:=aquadopp_resolve_serial(p_source_station,p_m_date);
 INSERT INTO rejected_observations(source_table,source_row_id,public_table,source_station,public_station,instrument_type,instrument_serial,m_date,public_parameter,qc_flag,rejection_reason,rejected_by,source_query_or_script) VALUES ('nortek_aquadopp',(SELECT row_id::bigint FROM nortek_aquadopp WHERE station=p_source_station AND m_date=p_m_date),'nortek_aquadopp',p_source_station,v_public,'Nortek Aquadopp',v_serial,p_m_date,p_public_parameter,p_qc_flag,p_rejection_reason,p_rejected_by,p_source_query_or_script) RETURNING rejection_id INTO v_id;
 PERFORM aquadopp_apply_active_rejections(p_source_station,v_serial,p_m_date); RETURN v_id; END $$;
CREATE FUNCTION reinstate_aquadopp_public_parameter(p_source_station varchar,p_serial_number_aquadopp varchar,p_m_date timestamptz,p_public_parameter varchar,p_reinstated_by varchar DEFAULT current_user,p_reinstatement_reason varchar DEFAULT 'reinstated') RETURNS void LANGUAGE plpgsql AS $$
BEGIN UPDATE rejected_observations SET active=false,reinstated_at=now(),reinstated_by=p_reinstated_by,reinstatement_reason=p_reinstatement_reason WHERE active AND source_table='nortek_aquadopp' AND public_table='nortek_aquadopp' AND instrument_type='Nortek Aquadopp' AND source_station=p_source_station AND m_date=p_m_date AND public_parameter=p_public_parameter; IF NOT FOUND THEN RAISE EXCEPTION 'active Aquadopp rejection not found'; END IF; END $$;
CREATE FUNCTION aquadopp_guard_public_parameter_write() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_source varchar;r record;BEGIN
 IF NEW.station !~ '^.+-WQ$' THEN RETURN NEW; END IF;v_source:=aquadopp_source_station(NEW.station);
 IF EXISTS(SELECT 1 FROM rejected_observations WHERE active AND source_table='nortek_aquadopp' AND public_table='nortek_aquadopp' AND instrument_type='Nortek Aquadopp' AND source_station=v_source AND public_station=NEW.station AND m_date=NEW.m_date) AND NOT EXISTS(SELECT 1 FROM nortek_aquadopp WHERE station=v_source AND m_date=NEW.m_date) THEN RAISE EXCEPTION 'Aquadopp public write has no matching private observation'; END IF;
 FOR r IN SELECT * FROM rejected_observations WHERE active AND source_table='nortek_aquadopp' AND public_table='nortek_aquadopp' AND instrument_type='Nortek Aquadopp' AND source_station=v_source AND m_date=NEW.m_date LOOP IF r.public_parameter='current_speed' THEN NEW.current_speed:=NULL;NEW.qc_current_speed:=r.qc_flag; ELSIF r.public_parameter='current_direction' THEN NEW.current_direction:=NULL;NEW.qc_current_direction:=r.qc_flag; END IF; END LOOP;RETURN NEW;END $$;
CREATE FUNCTION aquadopp_reapply_rejections_after_private_write() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN IF NEW.station !~ '^_.+_AQUADOPP$' THEN RETURN NEW;END IF;IF EXISTS(SELECT 1 FROM rejected_observations WHERE active AND source_table='nortek_aquadopp' AND public_table='nortek_aquadopp' AND instrument_type='Nortek Aquadopp' AND source_station=NEW.station AND m_date=NEW.m_date) THEN PERFORM aquadopp_apply_active_rejections(NEW.station,NULL,NEW.m_date);END IF;RETURN NEW;END $$;
CREATE TRIGGER aquadopp_guard_rejected_public_parameters BEFORE INSERT OR UPDATE ON nortek_aquadopp FOR EACH ROW EXECUTE FUNCTION aquadopp_guard_public_parameter_write();
CREATE TRIGGER aquadopp_reapply_rejected_public_parameters AFTER INSERT OR UPDATE ON nortek_aquadopp FOR EACH ROW EXECUTE FUNCTION aquadopp_reapply_rejections_after_private_write();
